#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Run from — and store secrets in — the prototype folder next to this script.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
cd "$SCRIPT_DIR"

TOTAL_STAGES=5
TOTAL_MINUTES=12

banner "CVM #1278 — validate the Blob → Buffer → TikTok transport"

# ── Stage 1: Buffer — connect TikTok + mint an API key ────────────────────
stage "Buffer — connect TikTok & mint API key" 4
say "We need a Buffer personal API key, and your TikTok channel connected in Buffer."
open_url "https://publish.buffer.com"
step "If TikTok isn't connected yet: add it as a channel (Channels → Connect a channel → TikTok)."
step "Then open Settings → API (developers.buffer.com/guides/authentication has the exact spot)."
step "Create / copy your personal API key. Treat it like a password."
note "Confirmed mintable on the Free tier (#1279)."
ask_secret BUFFER_API_KEY "Paste your Buffer API key (hidden):"
if [[ -z "${BUFFER_API_KEY:-}" ]]; then
  warn "No key entered — the post stages will fail. Re-run when you have it."
else
  write_env BUFFER_API_KEY "$BUFFER_API_KEY"
fi
pause "TikTok channel connected in Buffer? Press Enter once it's showing."

# ── Stage 2: Vercel — Blob read/write token ───────────────────────────────
stage "Vercel — Blob read/write token" 3
say "We upload the .mp4 to Vercel Blob to get a public URL Buffer can pull."
open_url "https://vercel.com/dashboard/stores"
step "Open (or create) a Blob store: Storage → Create / select a Blob store."
step "In the store, find the read/write token (Quickstart / '.env.local' snippet, or"
step "  Project → Settings → Environment Variables) — the value of BLOB_READ_WRITE_TOKEN."
ask_secret BLOB_READ_WRITE_TOKEN "Paste BLOB_READ_WRITE_TOKEN (hidden):"
if [[ -z "${BLOB_READ_WRITE_TOKEN:-}" ]]; then
  warn "No token entered — the upload will fail. Re-run when you have it."
else
  write_env BLOB_READ_WRITE_TOKEN "$BLOB_READ_WRITE_TOKEN"
fi

# Make the two secrets available to the npm commands this wizard runs next.
export BUFFER_API_KEY="${BUFFER_API_KEY:-}"
export BLOB_READ_WRITE_TOKEN="${BLOB_READ_WRITE_TOKEN:-}"

# ── Stage 3: install the script's dependencies ────────────────────────────
stage "Install dependencies" 1
say "Installing @vercel/blob + tsx for the validation script (once)."
if npm install; then
  note "dependencies ready."
else
  warn "npm install failed — fix the error above, then re-run this wizard."
fi

# ── Stage 4: find the TikTok channel id ───────────────────────────────────
stage "Find your TikTok channel id" 2
say "Listing your Buffer channels — this also answers 'is TikTok visible via the API?'"
if npm run --silent channels; then
  :
else
  warn "channels query failed (see above). Common cause: wrong API key or no org — you can pass --org later."
fi
step "Copy the id printed next to your TikTok channel above."
ask CHANNEL_ID "Paste the TikTok channel id:"
[[ -n "${CHANNEL_ID:-}" ]] && write_env CHANNEL_ID "$CHANNEL_ID"

# ── Stage 5: post the test video ──────────────────────────────────────────
stage "Post the test video to TikTok" 2
say "Now the real thing: upload the clip, createPost, poll to sent."
note "Use the >100MB clip in ~/Desktop/cvm-tiktok-test/ — proving >100MB is the whole point."
ask MP4_PATH "Full path to the test .mp4:"
ask CAPTION "Caption to post (test verbatim-landing, e.g. 'CVM test #test'):"

SCHEDULING="notification"
if confirm "Test AUTO-PUBLISH? (y = schedulingType=automatic + share now · n = reminder mode)"; then
  SCHEDULING="automatic"
fi
say "Scheduling: $SCHEDULING"

if [[ -z "${CHANNEL_ID:-}" || -z "${MP4_PATH:-}" || -z "${CAPTION:-}" ]]; then
  warn "Missing channel id / mp4 path / caption — skipping the post. Re-run to try again."
elif confirm "Post now to your real TikTok via Buffer? (SELF_ONLY-safe; you can delete it after)"; then
  # shellcheck disable=SC2086
  npm run --silent validate -- "$MP4_PATH" "$CAPTION" --channel "$CHANNEL_ID" --scheduling "$SCHEDULING" --share-now \
    || warn "validate exited non-zero — read the output above; the blob may still be live (delete manually if so)."
else
  note "Skipped posting. When ready, run:"
  note "  npm run validate -- \"$MP4_PATH\" \"$CAPTION\" --channel $CHANNEL_ID --scheduling $SCHEDULING --share-now"
fi

finish
say "Now eyeball TikTok and report on #1278:"
note "  - caption verbatim?  - auto-published or reminder?  - >100MB accepted?  - terminal status?"
printf '\n'
