#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — the PlanetScale + Vercel cutover for the local/remote split.
# Spec #1536, PR #1542, runbook docs/planetscale-cutover.md, ADR 0025.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

# The wizard runs against the repo it lives in, and the monorepo keeps ONE .env
# at the workspace root — apps/local, apps/remote and cvm all read that file.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
ENV_FILE="$REPO_ROOT/.env"

LOCAL_CONTAINER="${LOCAL_CONTAINER:-ai-app-template-postgres}"
WORK_DIR="$REPO_ROOT/.cutover"

# write_env_quoted KEY VALUE — .env in this repo quotes its connection strings,
# and a Postgres URL can carry characters an unquoted value would not survive.
# Strips any quotes it is given first, so a re-run cannot double them up.
write_env_quoted() {
  local value="$2"
  value="${value%\"}"; value="${value#\"}"
  write_env "$1" "\"$value\""
}

# unquote "..." — a value read back out of .env, with its quotes taken off.
unquote() { local v="$1"; v="${v%\"}"; v="${v#\"}"; printf '%s' "$v"; }

# die "..." — stop the wizard where a later stage could not be trusted.
die() { printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET"; exit 1; }

banner "Course Video Manager — local/remote cutover"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight — check the ground, then back it up"

say "PR #1542 split this repo into apps/local, apps/remote and packages/core."
say "The code has landed. Everything left is infrastructure, and this wizard"
say "is that part."
printf '\n'
warn "cvm is DEAD on this machine until stage 10. It now reaches the domain"
note "  data only over HTTP, and CVM_API_URL/CVM_API_TOKEN do not exist yet."
printf '\n'

[[ -f "$ENV_FILE" ]] || die "no .env at $ENV_FILE — this is not the repo root."

LOCAL_DATABASE_URL="$(unquote "$(_existing DATABASE_URL || true)")"
[[ -n "$LOCAL_DATABASE_URL" ]] || die "DATABASE_URL is not set in $ENV_FILE."
note "current DATABASE_URL → ${LOCAL_DATABASE_URL%%\?*}"

docker info >/dev/null 2>&1 || die "Docker is not running — the local database is in it."
docker ps --format '{{.Names}}' | grep -qx "$LOCAL_CONTAINER" \
  || die "container '$LOCAL_CONTAINER' is not running. Start it, or re-run with LOCAL_CONTAINER=<name>."
note "local Postgres container '$LOCAL_CONTAINER' is up"

mkdir -p "$WORK_DIR"
cp "$ENV_FILE" "$WORK_DIR/env.backup"
note "backed up .env → $WORK_DIR/env.backup"

say ""
say "Taking a full dump of the local database now, BEFORE anything moves."
say "This is both the thing we restore into PlanetScale and the way back."
DUMP_FILE="$WORK_DIR/cvm-local-$(date +%Y%m%d-%H%M%S).sql"
# The container's pg_dump matches the server it dumps (17); the host's client
# is older, and an older pg_dump refuses a newer server outright.
docker exec "$LOCAL_CONTAINER" pg_dump "$LOCAL_DATABASE_URL" --no-owner --no-acl > "$DUMP_FILE" \
  || die "pg_dump failed — nothing has changed, fix the connection and re-run."
printf '  %s✓ dumped%s %s (%s)\n' "$GREEN" "$RESET" "$DUMP_FILE" "$(du -h "$DUMP_FILE" | cut -f1)"
note "this dump carries the drizzle bookkeeping too, so the restored database"
note "knows exactly which migrations it has already had."
pause "Press Enter to continue"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "PlanetScale — create the database"

say "PS-5, London, Postgres 17. The spec's sizing: the whole database is ~81 MB."
open_url "https://app.planetscale.com/"
step "Create a new Postgres database."
step "Cluster size PS-5. Region: London (eu-west-2)."
step "Postgres version: 17. CHANGE THIS — the dropdown defaults to the newest."
step "Once it is up, open Settings → Backups."
step "Set the backup schedule to DAILY, retained 30 days."
printf '\n'
note "17 because the local container is 17.0 and this wizard restores a dump"
note "taken by its pg_dump. A dump from 18 cannot be restored INTO a 17 server,"
note "so choosing 18 would weld shut the revert path the next week depends on."
note "PlanetScale has no in-place major upgrade, but at 81 MB moving to 18 later"
note "is a minute of data and a calm afternoon — not this irreversible step."
printf '\n'
note "Daily, not weekly, and this is the one setting worth being fussy about:"
note "a 30-day window over WEEKLY backups means replaying up to seven days of"
note "WAL on restore — hours. Daily keeps a restore near an hour. At 81 MB the"
note "30-day window sits inside the included 2x-disk allowance, so it is free."
printf '\n'
confirm "Database created, daily backups retained 30 days?" \
  || die "Come back when it is up — nothing has changed yet."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "PlanetScale — two roles, not one"

say "Create TWO roles. Each one gives you its own connection string, and which"
say "role a string belongs to is what the next stage is really asking."
printf '\n'
printf '  %scvm-migrate%s — tick ONLY the last permission in the list:\n' "$BOLD" "$RESET"
note "    \"Create, modify, and drop databases, users, roles, tables,"
note "     schemas, and all other objects.\""
note "  Used by the restore below, and after that by exactly one thing"
note "  forever: the apps/remote deploy's vercel-build step."
printf '\n'
printf '  %scvm-app%s — tick EXACTLY TWO:\n' "$BOLD" "$RESET"
note "    \"Read data from all tables, views, and sequences.\""
note "    \"Write data to all tables, views, and sequences.\""
note "  Used by every application query, in apps/local and apps/remote."
printf '\n'
say "Leave the other nine unticked. They are monitoring, maintenance and"
say "replication — PlanetScale's dashboard and autovacuum cover all of it."
printf '\n'
note "Why split: DATABASE_URL ends up in .env, in two Vercel variables and in"
note "every runtime connection. Splitting makes the string that is EVERYWHERE"
note "incapable of dropping a table, and leaves DDL to the one string a single"
note "deploy step touches. Those two data roles apply to all tables whatever"
note "owns them, so nothing needs GRANTing after a migration."
printf '\n'
note "If the dashboard fights you, one admin role for both strings is a fine"
note "fallback — the spec does not require the split. Do not lose an hour here."
printf '\n'
confirm "Both roles created?" || die "Come back when they exist."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "PlanetScale — the two connection strings"

say "A hosted Postgres hands out two kinds, and this repo uses both differently:"
printf '\n'
step "DATABASE_URL        — POOLER (PgBouncer), as cvm-app. Every query."
step "DIRECT_DATABASE_URL — PRIMARY, as cvm-migrate. Migrations only."
printf '\n'
note "Migrations cannot go through a transaction-mode pooler: it cannot carry"
note "session state that DDL needs — advisory locks, SET, prepared statements."
printf '\n'
step "In the PlanetScale dashboard: Connect → Postgres/psql format."
step "Choose role cvm-app, then copy its POOLED connection string."
ask_secret PS_POOLED_URL "Paste the POOLED (cvm-app) connection string:"
[[ -n "$PS_POOLED_URL" ]] || die "no pooled connection string given."
step "Now switch to role cvm-migrate and copy its DIRECT connection string."
ask_secret PS_DIRECT_URL "Paste the DIRECT (cvm-migrate) connection string:"
[[ -n "$PS_DIRECT_URL" ]] || die "no direct connection string given."

PS_POOLED_URL="$(unquote "$PS_POOLED_URL")"
PS_DIRECT_URL="$(unquote "$PS_DIRECT_URL")"
if [[ "$PS_POOLED_URL" == "$PS_DIRECT_URL" ]]; then
  warn "those two are identical — check you copied the pooled and the direct one."
fi
printf '  %s✓%s held in memory. They are written to .env at stage 8, not before.\n' "$GREEN" "$RESET"

# The dump waiting on disk was written by pg_dump 17. Restoring it into a
# server OLDER than that is unsupported, and into a NEWER one costs the way
# back — a dump taken there could never return to the local 17 container.
# Cheap to check now; expensive to discover at stage 7.
printf '\n'
if command -v psql >/dev/null 2>&1; then
  # The pooled string is the one every query will use for the next year, and
  # it is the easiest of the two to paste from the wrong role. Prove it logs in
  # while a bad paste still costs nothing.
  if psql "$PS_POOLED_URL" -tAc 'select 1' >/dev/null 2>&1; then
    printf '  %s✓ the pooled (cvm-app) string connects%s\n' "$GREEN" "$RESET"
  else
    warn "the POOLED string does not connect — check the role and re-copy it."
    confirm "Go on anyway?" || die "Stopped: fix the pooled connection string."
  fi
  PS_VERSION="$(psql "$PS_DIRECT_URL" -tAc 'show server_version;' 2>/dev/null | cut -d. -f1 || true)"
  if [[ -z "$PS_VERSION" ]]; then
    warn "could not reach the database with that direct string — check it before going on."
  elif [[ "$PS_VERSION" == "17" ]]; then
    printf '  %s✓ PlanetScale is Postgres %s — matches the local container%s\n' "$GREEN" "$PS_VERSION" "$RESET"
  else
    warn "PlanetScale is Postgres $PS_VERSION; the local container is 17."
    note "  Newer: the restore will work, but a dump taken there can never go"
    note "  back into your local 17 container — the revert path loses its data."
    note "  Older: the restore will likely fail outright at stage 7."
    note "  There is no in-place major upgrade, so this is decided now."
    confirm "Go on with Postgres $PS_VERSION anyway?" \
      || die "Recreate the database on Postgres 17 and re-run."
  fi
else
  note "no psql on this machine — skipping the version check. Confirm by eye"
  note "that the database you created is Postgres 17."
fi
pause "Press Enter to continue"

# ── 5 ─────────────────────────────────────────────────────────────────────────
stage "Migrate the empty database"

say "This is the ONE time migrations are applied by hand. From here on the"
say "apps/remote deploy applies them and nothing else does — two writers racing"
say "to alter the production schema is the failure that rule exists to prevent."
printf '\n'
note "Running against the EMPTY database first, so the schema DDL is proved on"
note "its own before any data is in the way."
printf '\n'
confirm "Run the migrations against PlanetScale now?" || die "Stopped before migrating."
DIRECT_DATABASE_URL="$PS_DIRECT_URL" DATABASE_URL="$PS_DIRECT_URL" \
  pnpm --filter @cvm/core run db:migrate \
  || die "Migrations failed. The database is new and empty — fix and re-run."
printf '  %s✓ migrations applied%s\n' "$GREEN" "$RESET"
pause "Press Enter to continue"

# ── 6 ─────────────────────────────────────────────────────────────────────────
stage "Verify the risky schema features"

say "PGlite cannot prove hosted compatibility, so these are checked against the"
say "real database. Read-only — it queries the catalogue and writes nothing."
printf '\n'
note "What is at stake: COLLATE \"C\" (Fractional Index ordering), generated"
note "tsvector STORED columns and their GIN indexes (Diagram search), partial"
note "unique indexes (WHERE NOT archived), and text[] (Lesson dependencies)."
note "Postgres core, but unlisted rather than promised by PlanetScale."
printf '\n'
VERIFY_OUT="$WORK_DIR/verify-features.txt"
set +e
DIRECT_DATABASE_URL="$PS_DIRECT_URL" DATABASE_URL="$PS_DIRECT_URL" \
  pnpm run db:verify-features 2>&1 | tee "$VERIFY_OUT"
VERIFY_STATUS=${PIPESTATUS[0]}
set -e
printf '\n'
if [[ $VERIFY_STATUS -ne 0 ]]; then
  warn "A feature FAILED. Do not cut over."
  note "Output saved to $VERIFY_OUT — paste it onto issue #1537 and stop here."
  die "Schema features unsupported."
fi
printf '  %s✓ all schema features verified%s\n' "$GREEN" "$RESET"
note "saved to $VERIFY_OUT"
step "Paste that output onto issue #1537 — the spec asks for the record."
pause "Press Enter to continue"

# ── 7 ─────────────────────────────────────────────────────────────────────────
stage "Move the data"

say "The dump from stage 1 carries the schema, the data AND drizzle's record of"
say "which migrations have run. So the cleanest restore is into a database with"
say "nothing in it — we drop the schema we just migrated and load the dump over"
say "the top, then migrate again to catch the one migration the local database"
say "never had (0013_api_token)."
printf '\n'
note "Restoring schema-and-data together also sidesteps the trap in a data-only"
note "restore: it does not order tables by foreign key, so it fails halfway."
printf '\n'
warn "This DROPS everything in the PlanetScale database. It is minutes old and"
note "  holds no data — your own data is still local and untouched — but say so."
printf '\n'
confirm "Drop the PlanetScale schema and restore the dump?" || die "Stopped before touching the data."

# Which psql can reach PlanetScale? The container's client matches the server
# the dump came from, so it is preferred; but the container may have no route
# out, in which case the host's client does the job just as well — psql only
# sends SQL, so its version matters far less than pg_dump's did.
if docker exec -i "$LOCAL_CONTAINER" psql "$PS_DIRECT_URL" -c 'select 1' >/dev/null 2>&1; then
  psql_ps() { docker exec -i "$LOCAL_CONTAINER" psql "$PS_DIRECT_URL" "$@"; }
  note "reaching PlanetScale through the container's psql"
elif command -v psql >/dev/null 2>&1 && psql "$PS_DIRECT_URL" -c 'select 1' >/dev/null 2>&1; then
  psql_ps() { psql "$PS_DIRECT_URL" "$@"; }
  note "the container has no route out — using this machine's psql instead"
else
  die "Nothing here can reach PlanetScale with psql. Check the direct string."
fi

# Dropping the objects one by one rather than dropping the schema: `public` is
# owned by pg_database_owner, so a migration role that is not a superuser can
# fill it but cannot drop it. Everything below was created by that role at
# stage 5, so it owns all of it. The dump recreates `drizzle` but never
# `public` — pg_dump does not emit it — so public must survive.
psql_ps -v ON_ERROR_STOP=1 <<'SQL' || die "Could not clear the database."
DROP SCHEMA IF EXISTS drizzle CASCADE;
DO $$
DECLARE r record;
BEGIN
  FOR r IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' LOOP
    EXECUTE format('DROP TABLE IF EXISTS public.%I CASCADE', r.tablename);
  END LOOP;
  FOR r IN SELECT sequencename FROM pg_sequences WHERE schemaname = 'public' LOOP
    EXECUTE format('DROP SEQUENCE IF EXISTS public.%I CASCADE', r.sequencename);
  END LOOP;
END $$;
SQL
printf '  %s✓ cleared%s\n' "$GREEN" "$RESET"

say "Restoring $(du -h "$DUMP_FILE" | cut -f1) — the spec says under a minute."
psql_ps -v ON_ERROR_STOP=1 -q < "$DUMP_FILE" \
  || die "Restore failed. Your local database is untouched — that is still the live one."
printf '  %s✓ data restored%s\n' "$GREEN" "$RESET"

say "Applying any migration the local database had not had:"
DIRECT_DATABASE_URL="$PS_DIRECT_URL" DATABASE_URL="$PS_DIRECT_URL" \
  pnpm --filter @cvm/core run db:migrate \
  || die "Migration after restore failed."
printf '  %s✓ schema up to date%s\n' "$GREEN" "$RESET"
pause "Press Enter to continue"

# ── 8 ─────────────────────────────────────────────────────────────────────────
stage "Point apps/local at the hosted database"

say "apps/local connects to the database DIRECTLY — the Video Editor and the"
say "Publish flow do not pay a network hop to reach their own data."
printf '\n'
write_env_quoted DATABASE_URL "$PS_POOLED_URL"
write_env_quoted DIRECT_DATABASE_URL "$PS_DIRECT_URL"
if ! grep -q '^# CUTOVER REVERT' "$ENV_FILE"; then
  {
    printf '\n# CUTOVER REVERT — the local container stays for at least a week.\n'
    printf '# Reverting is this one line: put it back as DATABASE_URL and drop\n'
    printf '# DIRECT_DATABASE_URL. See docs/planetscale-cutover.md.\n'
    printf '# LOCAL_DATABASE_URL_WAS="%s"\n' "$LOCAL_DATABASE_URL"
  } >> "$ENV_FILE"
  note "recorded the old local string in .env, commented out, as the way back"
fi
printf '\n'
warn "Do NOT stop or delete the local Postgres container."
note "  It stays until the hosted database has carried a week of real use."
printf '\n'
step "Restart the local app (pnpm dev) and click around the Course view."
step "Watch the browser network panel and note the loader timings."
step "Record those numbers on issue #1537 — the spec wants the decision to"
step "  keep going based on a measurement, not a feeling."
note "If latency is bad, the fix is batching inside packages/core, not reversing."
pause "Press Enter when the app is talking to the hosted database"

# ── 9 ─────────────────────────────────────────────────────────────────────────
stage "Deploy apps/remote to Vercel"

say "A small Hono app: the RPC API, and nothing else. No UI is being deployed."
open_url "https://vercel.com/new"
step "Import this repository as a NEW project (separate from any existing one)."
step "Root Directory: apps/remote"
step "Framework Preset: Hono"
step "Leave 'Include files outside the root directory' ON — it is a pnpm"
step "  workspace and the build needs packages/core."
step "Set NO Ignored Build Step. Leave it empty."
printf '\n'
note "Vercel's built-in unaffected-project skipping is what stops a filming"
note "commit in apps/local triggering an API deploy, and unlike turbo-ignore it"
note "does not consume a concurrent build slot. turbo-ignore is deprecated."
printf '\n'
step "Add two Environment Variables, for all environments:"
printf '\n'
printf '    %sDATABASE_URL%s        the POOLED string\n' "$BOLD" "$RESET"
printf '    %sDIRECT_DATABASE_URL%s the DIRECT string\n' "$BOLD" "$RESET"
printf '\n'
note "They are on your clipboard's history from stage 4; both are also in"
note "  $ENV_FILE now."
printf '\n'
note "The vercel-build script takes precedence over the preset's build command,"
note "and it is where the migrations run — this deploy is the only thing in the"
note "world allowed to apply them."
printf '\n'
step "Deploy. Wait for it to go green."
printf '\n'
confirm "Deployed successfully?" || die "Fix the deploy, then re-run from here."
step "Copy the project's production URL (https://....vercel.app)."
ask CVM_API_URL "Paste the production URL:"
[[ -n "$CVM_API_URL" ]] || die "no API URL given."
CVM_API_URL="${CVM_API_URL%/}"
write_env_quoted CVM_API_URL "$CVM_API_URL"
pause "Press Enter to continue"

# ── 10 ────────────────────────────────────────────────────────────────────────
stage "Mint an API token"

say "Access to the API is a token you mint deliberately — not a secret copied"
say "out of a file. It is stored as a SHA-256 hash and shown to you ONCE."
printf '\n'
step "Start the local app if it is not running:  pnpm dev"
pause "Press Enter once it is up"
open_url "http://localhost:5173/api-tokens"
step "Mint a token. Name it for the machine that will hold it — this one is"
step "  yours, so something like 'matt laptop'."
step "Copy the secret NOW. Nothing stores it — not the page, not the database."
printf '\n'
note "If you navigate away before copying it, the token is unusable and the"
note "honest fix is to revoke it and mint another. Default expiry is 90 days."
printf '\n'
ask_secret CVM_API_TOKEN "Paste the token (cvm_..._...):"
[[ -n "$CVM_API_TOKEN" ]] || die "no token given."
CVM_API_TOKEN="$(unquote "$CVM_API_TOKEN")"
[[ "$CVM_API_TOKEN" == cvm_* ]] || warn "that does not start with 'cvm_' — check it."
write_env_quoted CVM_API_TOKEN "$CVM_API_TOKEN"
printf '\n'
say "And declaring this machine as the author's:"
write_env_quoted CVM_LOCAL_MACHINE "true"
note "cvm file, cvm course readiness and cvm course publish need the finished"
note "videos directory and ffmpeg. The machine is DECLARED, never detected — a"
note "box that says nothing is treated as remote and refused with exit 7."
printf '\n'
warn "NEVER set CVM_LOCAL_MACHINE on a remote box."
pause "Press Enter to continue"

# ── 11 ────────────────────────────────────────────────────────────────────────
stage "Smoke test — cvm over the wire"

say "Your own cvm now takes exactly the route an agent takes. That is the point"
say "of the design: the path the agent depends on is the path you exercise daily."
printf '\n'
set +e
CVM_API_URL="$CVM_API_URL" CVM_API_TOKEN="$CVM_API_TOKEN" \
  node "$REPO_ROOT/apps/local/app/cli/bin.mjs" search "typescript" 2>&1 | head -20
SMOKE_STATUS=${PIPESTATUS[0]}
set -e
printf '\n'
if [[ $SMOKE_STATUS -eq 0 ]]; then
  printf '  %s✓ cvm reached the deployed API and got an answer%s\n' "$GREEN" "$RESET"
else
  warn "cvm exited $SMOKE_STATUS. The exit code names the fix:"
  note "  5 — authentication. Mint a new token."
  note "  6 — out-of-date checkout. git pull on this box."
  note "  7 — the command needs the author's machine. That is a STOP, not a retry."
  note "Run 'cvm --help' — it documents all three."
fi
pause "Press Enter to continue"

# ── 12 ────────────────────────────────────────────────────────────────────────
stage "Aftercare — what is true now, and what to watch"

say "What changed:"
step "The domain database is hosted. There is one, in the cloud."
step "Every cvm invocation goes over HTTP. cvm stops working when the deployed"
step "  app is down — accepted, because the CLI is not how filming happens."
step "cvm writes no longer need the dev server running."
printf '\n'
say "What did NOT change: filming, shipping, the Video Editor, Recording"
say "Sessions, Clip capture, Transcription, the Publish flow, the Diagram"
say "Playground. Those were out of scope and are untouched."
printf '\n'
warn "The backup guarantee you just traded away, stated plainly:"
note "  The backup coordinator used to refuse every cvm write unless a fresh"
note "  dump could be taken, which made a write un-losable. That is now a"
note "  30-day recovery window with a restore of about an hour — and it was"
note "  given up at the moment an agent starts writing from a machine nobody"
note "  is watching. dump-service.ts and backup-coordinator.ts are deleted."
printf '\n'
say "Over the next week:"
step "Use it normally. Keep the local container. Reverting is one line in .env."
step "Record loader latency on issue #1537."
step "Retire nothing until the hosted database has carried a week of real use."
printf '\n'
say "When you give a remote box a token:"
step "Mint a SECOND token, named for that box. Do not reuse this one."
step "Set CVM_API_URL and CVM_API_TOKEN there as real environment variables."
step "There is no .env on that box, and NO CVM_LOCAL_MACHINE."
printf '\n'
warn "Tokens are unscoped in version one. A token grants every operation the"
note "  RPC surface exposes. ADR 0025: the day a token is handed to something"
note "  you did not write, scoping becomes urgent."
pause "Press Enter to finish"

finish
say "Runbook:  docs/planetscale-cutover.md"
say "Decision: docs/adr/0025-local-remote-split-one-http-transport.md"
say "The API:  apps/remote/README.md"
printf '\n'
